CREATE TABLE TWSS_PICTURES(
	ID NUMBER NOT NULL,
	UUID VARCHAR2(250 BYTE) NOT NULL,
	USERNAME VARCHAR2(250 BYTE) NOT NULL,
    NAME VARCHAR2(250 BYTE) NOT NULL,
    FILE_TYPE VARCHAR2(100 BYTE) NOT NULL,
    TYPE VARCHAR2(250 BYTE) NOT NULL,
    FILE_SIZE NUMBER NULL,
    VALUE BLOB NOT NULL,
    CREATED TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT TWSS_PICTURES_PK PRIMARY KEY (ID) ENABLE,
    CONSTRAINT TWSS_PICTURES_UUID_UQ UNIQUE (UUID)
);


CREATE SEQUENCE TWSS_PICTURES_SEQ;
 
CREATE TRIGGER TWSS_PICTURES_TRG
BEFORE INSERT ON TWSS_PICTURES
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TWSS_PICTURES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/